name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  unittests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['8.1', '8.2']

    name: PHP ${{ matrix.php }} unittests
    steps:
      - uses: actions/checkout@v3

      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      - uses: ramsey/composer-install@v2
        with:
          composer-options: "--no-interaction --no-suggest"

      - run: vendor/bin/phpunit
